### PR TITLE
Add fallback for Apple M1

### PR DESCRIPTION
**Pull request by borkdude**

### CODE REVIEW

**Comment by cap10morgan** [comment]
This works for me on my main dev machine, which is an M1. I'm going to try it out in a fresh macOS VM too to see what it does when you don't (yet) have Rosetta 2 installed. Hopefully it will just prompt to install it like other things do.

**Comment by borkdude** [comment]
Ah, thanks!

**Comment by cap10morgan** [comment]
OK sadly it does not offer to install Rosetta in the VM, but it does work once it's installed. You might want to say something along these lines in the docs somewhere:

If you see the error `Bad CPU type in executable`, you likely need to install Rosetta 2 on your Apple Silicon Mac. You can do that by opening Terminal and running this command: `softwareupdate --install-rosetta`

**Review by cap10morgan — APPROVED** [review]
🏵️

**Pull request merged**
